// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: warp.proto

package warpapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WarpApi_Attach_FullMethodName          = "/warpapi.WarpApi/Attach"
	WarpApi_Detach_FullMethodName          = "/warpapi.WarpApi/Detach"
	WarpApi_AddService_FullMethodName      = "/warpapi.WarpApi/AddService"
	WarpApi_GetService_FullMethodName      = "/warpapi.WarpApi/GetService"
	WarpApi_DelService_FullMethodName      = "/warpapi.WarpApi/DelService"
	WarpApi_Save_FullMethodName            = "/warpapi.WarpApi/Save"
	WarpApi_Poll_FullMethodName            = "/warpapi.WarpApi/Poll"
	WarpApi_Push_FullMethodName            = "/warpapi.WarpApi/Push"
	WarpApi_GetAttachedAddr_FullMethodName = "/warpapi.WarpApi/GetAttachedAddr"
	WarpApi_KeepAlive_FullMethodName       = "/warpapi.WarpApi/KeepAlive"
)

// WarpApiClient is the client API for WarpApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarpApiClient interface {
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*Empty, error)
	Detach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*Empty, error)
	AddService(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error)
	GetService(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResponse, error)
	DelService(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*Empty, error)
	Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*Empty, error)
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Empty, error)
	GetAttachedAddr(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAttachedAddrResponse, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (WarpApi_KeepAliveClient, error)
}

type warpApiClient struct {
	cc grpc.ClientConnInterface
}

func NewWarpApiClient(cc grpc.ClientConnInterface) WarpApiClient {
	return &warpApiClient{cc}
}

func (c *warpApiClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WarpApi_Attach_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) Detach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WarpApi_Detach_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) AddService(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WarpApi_AddService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) GetService(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, WarpApi_GetService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) DelService(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WarpApi_DelService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WarpApi_Save_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, WarpApi_Poll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WarpApi_Push_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) GetAttachedAddr(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAttachedAddrResponse, error) {
	out := new(GetAttachedAddrResponse)
	err := c.cc.Invoke(ctx, WarpApi_GetAttachedAddr_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpApiClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (WarpApi_KeepAliveClient, error) {
	stream, err := c.cc.NewStream(ctx, &WarpApi_ServiceDesc.Streams[0], WarpApi_KeepAlive_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &warpApiKeepAliveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WarpApi_KeepAliveClient interface {
	Recv() (*KeepAliveResponse, error)
	grpc.ClientStream
}

type warpApiKeepAliveClient struct {
	grpc.ClientStream
}

func (x *warpApiKeepAliveClient) Recv() (*KeepAliveResponse, error) {
	m := new(KeepAliveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WarpApiServer is the server API for WarpApi service.
// All implementations must embed UnimplementedWarpApiServer
// for forward compatibility
type WarpApiServer interface {
	Attach(context.Context, *AttachRequest) (*Empty, error)
	Detach(context.Context, *AttachRequest) (*Empty, error)
	AddService(context.Context, *AddRequest) (*Empty, error)
	GetService(context.Context, *Empty) (*GetResponse, error)
	DelService(context.Context, *DelRequest) (*Empty, error)
	Save(context.Context, *SaveReq) (*Empty, error)
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	Push(context.Context, *PushRequest) (*Empty, error)
	GetAttachedAddr(context.Context, *Empty) (*GetAttachedAddrResponse, error)
	KeepAlive(*KeepAliveRequest, WarpApi_KeepAliveServer) error
	mustEmbedUnimplementedWarpApiServer()
}

// UnimplementedWarpApiServer must be embedded to have forward compatible implementations.
type UnimplementedWarpApiServer struct {
}

func (UnimplementedWarpApiServer) Attach(context.Context, *AttachRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedWarpApiServer) Detach(context.Context, *AttachRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detach not implemented")
}
func (UnimplementedWarpApiServer) AddService(context.Context, *AddRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddService not implemented")
}
func (UnimplementedWarpApiServer) GetService(context.Context, *Empty) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedWarpApiServer) DelService(context.Context, *DelRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelService not implemented")
}
func (UnimplementedWarpApiServer) Save(context.Context, *SaveReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedWarpApiServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedWarpApiServer) Push(context.Context, *PushRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedWarpApiServer) GetAttachedAddr(context.Context, *Empty) (*GetAttachedAddrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttachedAddr not implemented")
}
func (UnimplementedWarpApiServer) KeepAlive(*KeepAliveRequest, WarpApi_KeepAliveServer) error {
	return status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedWarpApiServer) mustEmbedUnimplementedWarpApiServer() {}

// UnsafeWarpApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarpApiServer will
// result in compilation errors.
type UnsafeWarpApiServer interface {
	mustEmbedUnimplementedWarpApiServer()
}

func RegisterWarpApiServer(s grpc.ServiceRegistrar, srv WarpApiServer) {
	s.RegisterService(&WarpApi_ServiceDesc, srv)
}

func _WarpApi_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_Attach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).Attach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_Detach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).Detach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_Detach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).Detach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_AddService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).AddService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_AddService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).AddService(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).GetService(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_DelService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).DelService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_DelService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).DelService(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).Save(ctx, req.(*SaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_Poll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_GetAttachedAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpApiServer).GetAttachedAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarpApi_GetAttachedAddr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpApiServer).GetAttachedAddr(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarpApi_KeepAlive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeepAliveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WarpApiServer).KeepAlive(m, &warpApiKeepAliveServer{stream})
}

type WarpApi_KeepAliveServer interface {
	Send(*KeepAliveResponse) error
	grpc.ServerStream
}

type warpApiKeepAliveServer struct {
	grpc.ServerStream
}

func (x *warpApiKeepAliveServer) Send(m *KeepAliveResponse) error {
	return x.ServerStream.SendMsg(m)
}

// WarpApi_ServiceDesc is the grpc.ServiceDesc for WarpApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarpApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warpapi.WarpApi",
	HandlerType: (*WarpApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attach",
			Handler:    _WarpApi_Attach_Handler,
		},
		{
			MethodName: "Detach",
			Handler:    _WarpApi_Detach_Handler,
		},
		{
			MethodName: "AddService",
			Handler:    _WarpApi_AddService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _WarpApi_GetService_Handler,
		},
		{
			MethodName: "DelService",
			Handler:    _WarpApi_DelService_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _WarpApi_Save_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _WarpApi_Poll_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _WarpApi_Push_Handler,
		},
		{
			MethodName: "GetAttachedAddr",
			Handler:    _WarpApi_GetAttachedAddr_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeepAlive",
			Handler:       _WarpApi_KeepAlive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "warp.proto",
}
