// Code generated by protoc-gen-go. DO NOT EDIT.
// source: warp.proto

package warpapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceType int32

const (
	ServiceType_DEFAULT ServiceType = 0
	ServiceType_NAT     ServiceType = 1
	ServiceType_FNAT    ServiceType = 2
)

var ServiceType_name = map[int32]string{
	0: "DEFAULT",
	1: "NAT",
	2: "FNAT",
}

var ServiceType_value = map[string]int32{
	"DEFAULT": 0,
	"NAT":     1,
	"FNAT":    2,
}

func (x ServiceType) String() string {
	return proto.EnumName(ServiceType_name, int32(x))
}

func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{0}
}

type Protocol int32

const (
	Protocol_INVALID Protocol = 0
	Protocol_TCP     Protocol = 6
	Protocol_UDP     Protocol = 17
)

var Protocol_name = map[int32]string{
	0:  "INVALID",
	6:  "TCP",
	17: "UDP",
}

var Protocol_value = map[string]int32{
	"INVALID": 0,
	"TCP":     6,
	"UDP":     17,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{1}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ServiceKey struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol             Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=warpapi.Protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceKey) Reset()         { *m = ServiceKey{} }
func (m *ServiceKey) String() string { return proto.CompactTextString(m) }
func (*ServiceKey) ProtoMessage()    {}
func (*ServiceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{1}
}

func (m *ServiceKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceKey.Unmarshal(m, b)
}
func (m *ServiceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceKey.Marshal(b, m, deterministic)
}
func (m *ServiceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceKey.Merge(m, src)
}
func (m *ServiceKey) XXX_Size() int {
	return xxx_messageInfo_ServiceKey.Size(m)
}
func (m *ServiceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceKey.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceKey proto.InternalMessageInfo

func (m *ServiceKey) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServiceKey) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceKey) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_INVALID
}

type Session struct {
	ClientIp             string   `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort           uint32   `protobuf:"varint,2,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	VirtualIp            string   `protobuf:"bytes,3,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	VirtualPort          uint32   `protobuf:"varint,4,opt,name=virtual_port,json=virtualPort,proto3" json:"virtual_port,omitempty"`
	LocalIp              string   `protobuf:"bytes,5,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort            uint32   `protobuf:"varint,6,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RealIp               string   `protobuf:"bytes,7,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"`
	RealPort             uint32   `protobuf:"varint,8,opt,name=real_port,json=realPort,proto3" json:"real_port,omitempty"`
	Protocol             Protocol `protobuf:"varint,9,opt,name=protocol,proto3,enum=warpapi.Protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{2}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *Session) GetClientPort() uint32 {
	if m != nil {
		return m.ClientPort
	}
	return 0
}

func (m *Session) GetVirtualIp() string {
	if m != nil {
		return m.VirtualIp
	}
	return ""
}

func (m *Session) GetVirtualPort() uint32 {
	if m != nil {
		return m.VirtualPort
	}
	return 0
}

func (m *Session) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *Session) GetLocalPort() uint32 {
	if m != nil {
		return m.LocalPort
	}
	return 0
}

func (m *Session) GetRealIp() string {
	if m != nil {
		return m.RealIp
	}
	return ""
}

func (m *Session) GetRealPort() uint32 {
	if m != nil {
		return m.RealPort
	}
	return 0
}

func (m *Session) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_INVALID
}

type ServiceAttr struct {
	LocalIp              string   `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	RealPort             uint32   `protobuf:"varint,2,opt,name=real_port,json=realPort,proto3" json:"real_port,omitempty"`
	RealServerIps        []string `protobuf:"bytes,5,rep,name=real_server_ips,json=realServerIps,proto3" json:"real_server_ips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceAttr) Reset()         { *m = ServiceAttr{} }
func (m *ServiceAttr) String() string { return proto.CompactTextString(m) }
func (*ServiceAttr) ProtoMessage()    {}
func (*ServiceAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{3}
}

func (m *ServiceAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAttr.Unmarshal(m, b)
}
func (m *ServiceAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAttr.Marshal(b, m, deterministic)
}
func (m *ServiceAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAttr.Merge(m, src)
}
func (m *ServiceAttr) XXX_Size() int {
	return xxx_messageInfo_ServiceAttr.Size(m)
}
func (m *ServiceAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAttr.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAttr proto.InternalMessageInfo

func (m *ServiceAttr) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *ServiceAttr) GetRealPort() uint32 {
	if m != nil {
		return m.RealPort
	}
	return 0
}

func (m *ServiceAttr) GetRealServerIps() []string {
	if m != nil {
		return m.RealServerIps
	}
	return nil
}

type Service struct {
	Key                  *ServiceKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  *ServiceAttr `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{4}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetKey() *ServiceKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Service) GetVal() *ServiceAttr {
	if m != nil {
		return m.Val
	}
	return nil
}

type AddRequest struct {
	Type                 ServiceType  `protobuf:"varint,1,opt,name=type,proto3,enum=warpapi.ServiceType" json:"type,omitempty"`
	Key                  *ServiceKey  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Val                  *ServiceAttr `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{5}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetType() ServiceType {
	if m != nil {
		return m.Type
	}
	return ServiceType_DEFAULT
}

func (m *AddRequest) GetKey() *ServiceKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AddRequest) GetVal() *ServiceAttr {
	if m != nil {
		return m.Val
	}
	return nil
}

type DelRequest struct {
	Type                 ServiceType `protobuf:"varint,1,opt,name=type,proto3,enum=warpapi.ServiceType" json:"type,omitempty"`
	Key                  *ServiceKey `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{6}
}

func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (m *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(m, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetType() ServiceType {
	if m != nil {
		return m.Type
	}
	return ServiceType_DEFAULT
}

func (m *DelRequest) GetKey() *ServiceKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{7}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type AttachRequest struct {
	Type                 ServiceType `protobuf:"varint,1,opt,name=type,proto3,enum=warpapi.ServiceType" json:"type,omitempty"`
	Ip                   string      `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AttachRequest) Reset()         { *m = AttachRequest{} }
func (m *AttachRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()    {}
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{8}
}

func (m *AttachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRequest.Unmarshal(m, b)
}
func (m *AttachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRequest.Marshal(b, m, deterministic)
}
func (m *AttachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRequest.Merge(m, src)
}
func (m *AttachRequest) XXX_Size() int {
	return xxx_messageInfo_AttachRequest.Size(m)
}
func (m *AttachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRequest proto.InternalMessageInfo

func (m *AttachRequest) GetType() ServiceType {
	if m != nil {
		return m.Type
	}
	return ServiceType_DEFAULT
}

func (m *AttachRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type SaveReq struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveReq) Reset()         { *m = SaveReq{} }
func (m *SaveReq) String() string { return proto.CompactTextString(m) }
func (*SaveReq) ProtoMessage()    {}
func (*SaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{9}
}

func (m *SaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveReq.Unmarshal(m, b)
}
func (m *SaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveReq.Marshal(b, m, deterministic)
}
func (m *SaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveReq.Merge(m, src)
}
func (m *SaveReq) XXX_Size() int {
	return xxx_messageInfo_SaveReq.Size(m)
}
func (m *SaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveReq proto.InternalMessageInfo

func (m *SaveReq) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type PollRequest struct {
	Type                 ServiceType `protobuf:"varint,1,opt,name=type,proto3,enum=warpapi.ServiceType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PollRequest) Reset()         { *m = PollRequest{} }
func (m *PollRequest) String() string { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()    {}
func (*PollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{10}
}

func (m *PollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollRequest.Unmarshal(m, b)
}
func (m *PollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollRequest.Marshal(b, m, deterministic)
}
func (m *PollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollRequest.Merge(m, src)
}
func (m *PollRequest) XXX_Size() int {
	return xxx_messageInfo_PollRequest.Size(m)
}
func (m *PollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollRequest proto.InternalMessageInfo

func (m *PollRequest) GetType() ServiceType {
	if m != nil {
		return m.Type
	}
	return ServiceType_DEFAULT
}

type PollResponse struct {
	NatSessions          []*Session `protobuf:"bytes,1,rep,name=nat_sessions,json=natSessions,proto3" json:"nat_sessions,omitempty"`
	FnatSessions         []*Session `protobuf:"bytes,2,rep,name=fnat_sessions,json=fnatSessions,proto3" json:"fnat_sessions,omitempty"`
	TransportGroup       string     `protobuf:"bytes,12,opt,name=transport_group,json=transportGroup,proto3" json:"transport_group,omitempty"`
	Version              string     `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PollResponse) Reset()         { *m = PollResponse{} }
func (m *PollResponse) String() string { return proto.CompactTextString(m) }
func (*PollResponse) ProtoMessage()    {}
func (*PollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{11}
}

func (m *PollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollResponse.Unmarshal(m, b)
}
func (m *PollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollResponse.Marshal(b, m, deterministic)
}
func (m *PollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollResponse.Merge(m, src)
}
func (m *PollResponse) XXX_Size() int {
	return xxx_messageInfo_PollResponse.Size(m)
}
func (m *PollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PollResponse proto.InternalMessageInfo

func (m *PollResponse) GetNatSessions() []*Session {
	if m != nil {
		return m.NatSessions
	}
	return nil
}

func (m *PollResponse) GetFnatSessions() []*Session {
	if m != nil {
		return m.FnatSessions
	}
	return nil
}

func (m *PollResponse) GetTransportGroup() string {
	if m != nil {
		return m.TransportGroup
	}
	return ""
}

func (m *PollResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PushRequest struct {
	NatSessions          []*Session `protobuf:"bytes,1,rep,name=nat_sessions,json=natSessions,proto3" json:"nat_sessions,omitempty"`
	FnatSessions         []*Session `protobuf:"bytes,2,rep,name=fnat_sessions,json=fnatSessions,proto3" json:"fnat_sessions,omitempty"`
	TransportGroup       string     `protobuf:"bytes,12,opt,name=transport_group,json=transportGroup,proto3" json:"transport_group,omitempty"`
	Version              string     `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{12}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetNatSessions() []*Session {
	if m != nil {
		return m.NatSessions
	}
	return nil
}

func (m *PushRequest) GetFnatSessions() []*Session {
	if m != nil {
		return m.FnatSessions
	}
	return nil
}

func (m *PushRequest) GetTransportGroup() string {
	if m != nil {
		return m.TransportGroup
	}
	return ""
}

func (m *PushRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetAttachedAddrResponse struct {
	Addrs                []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttachedAddrResponse) Reset()         { *m = GetAttachedAddrResponse{} }
func (m *GetAttachedAddrResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttachedAddrResponse) ProtoMessage()    {}
func (*GetAttachedAddrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{13}
}

func (m *GetAttachedAddrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttachedAddrResponse.Unmarshal(m, b)
}
func (m *GetAttachedAddrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttachedAddrResponse.Marshal(b, m, deterministic)
}
func (m *GetAttachedAddrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttachedAddrResponse.Merge(m, src)
}
func (m *GetAttachedAddrResponse) XXX_Size() int {
	return xxx_messageInfo_GetAttachedAddrResponse.Size(m)
}
func (m *GetAttachedAddrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttachedAddrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttachedAddrResponse proto.InternalMessageInfo

func (m *GetAttachedAddrResponse) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

type KeepAliveRequest struct {
	IntervalSec          uint32   `protobuf:"varint,1,opt,name=interval_sec,json=intervalSec,proto3" json:"interval_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{14}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetIntervalSec() uint32 {
	if m != nil {
		return m.IntervalSec
	}
	return 0
}

type KeepAliveResponse struct {
	UptimeSec            uint64   `protobuf:"varint,1,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_926c500def4d6c70, []int{15}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

func (m *KeepAliveResponse) GetUptimeSec() uint64 {
	if m != nil {
		return m.UptimeSec
	}
	return 0
}

func init() {
	proto.RegisterEnum("warpapi.ServiceType", ServiceType_name, ServiceType_value)
	proto.RegisterEnum("warpapi.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*Empty)(nil), "warpapi.Empty")
	proto.RegisterType((*ServiceKey)(nil), "warpapi.ServiceKey")
	proto.RegisterType((*Session)(nil), "warpapi.Session")
	proto.RegisterType((*ServiceAttr)(nil), "warpapi.ServiceAttr")
	proto.RegisterType((*Service)(nil), "warpapi.Service")
	proto.RegisterType((*AddRequest)(nil), "warpapi.AddRequest")
	proto.RegisterType((*DelRequest)(nil), "warpapi.DelRequest")
	proto.RegisterType((*GetResponse)(nil), "warpapi.GetResponse")
	proto.RegisterType((*AttachRequest)(nil), "warpapi.AttachRequest")
	proto.RegisterType((*SaveReq)(nil), "warpapi.SaveReq")
	proto.RegisterType((*PollRequest)(nil), "warpapi.PollRequest")
	proto.RegisterType((*PollResponse)(nil), "warpapi.PollResponse")
	proto.RegisterType((*PushRequest)(nil), "warpapi.PushRequest")
	proto.RegisterType((*GetAttachedAddrResponse)(nil), "warpapi.GetAttachedAddrResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "warpapi.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "warpapi.KeepAliveResponse")
}

func init() { proto.RegisterFile("warp.proto", fileDescriptor_926c500def4d6c70) }

var fileDescriptor_926c500def4d6c70 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xc6, 0x8e, 0x37, 0x8e, 0x8f, 0x93, 0x6c, 0x76, 0x28, 0xd4, 0x0d, 0xaa, 0x48, 0x2d, 0xb1,
	0x84, 0x8a, 0x6e, 0xdb, 0xac, 0x2a, 0x2e, 0x7a, 0x65, 0x9a, 0x76, 0x65, 0xb5, 0xaa, 0x2c, 0x67,
	0x0b, 0x08, 0x09, 0x45, 0xc6, 0x99, 0x65, 0x2d, 0xbc, 0xf1, 0x74, 0x3c, 0x09, 0xca, 0x03, 0xf0,
	0x1c, 0xdc, 0xf2, 0x10, 0xf0, 0x6e, 0x68, 0xce, 0xd8, 0x8e, 0xe3, 0x2c, 0x5a, 0xf6, 0x82, 0x8b,
	0xde, 0x8d, 0xbf, 0x73, 0xbe, 0xf3, 0x33, 0x73, 0xbe, 0x63, 0x80, 0xdf, 0x22, 0xce, 0x4e, 0x18,
	0xcf, 0x44, 0x46, 0x4c, 0x79, 0x8e, 0x58, 0xe2, 0x9a, 0x70, 0xf0, 0xf2, 0x8a, 0x89, 0x8d, 0x3b,
	0x07, 0x98, 0x51, 0xbe, 0x4e, 0x62, 0xfa, 0x9a, 0x6e, 0x48, 0x1f, 0xf4, 0x84, 0x39, 0xda, 0x48,
	0x1b, 0x5b, 0xa1, 0x9e, 0x30, 0x42, 0xc0, 0x60, 0x19, 0x17, 0x8e, 0x3e, 0xd2, 0xc6, 0xbd, 0x10,
	0xcf, 0xe4, 0x11, 0x74, 0x30, 0x58, 0x9c, 0xa5, 0x4e, 0x6b, 0xa4, 0x8d, 0xfb, 0x93, 0xa3, 0x93,
	0x22, 0xec, 0x49, 0x50, 0x18, 0xc2, 0xca, 0xc5, 0xfd, 0x53, 0x07, 0x73, 0x46, 0xf3, 0x3c, 0xc9,
	0x96, 0xe4, 0x33, 0xb0, 0xe2, 0x34, 0xa1, 0x4b, 0x31, 0xaf, 0xb2, 0x74, 0x14, 0xe0, 0x33, 0xf2,
	0x39, 0xd8, 0x85, 0xb1, 0x96, 0x12, 0x14, 0x14, 0xc8, 0xc4, 0xf7, 0x01, 0xd6, 0x09, 0x17, 0xab,
	0x28, 0x95, 0xf4, 0x16, 0xd2, 0xad, 0x02, 0xf1, 0x19, 0x79, 0x00, 0xdd, 0xd2, 0x8c, 0x01, 0x0c,
	0x0c, 0x60, 0x17, 0x18, 0x46, 0xb8, 0x07, 0x9d, 0x34, 0x8b, 0x15, 0xff, 0x00, 0xf9, 0x26, 0x7e,
	0xfb, 0x4c, 0x06, 0x57, 0x26, 0xe4, 0xb6, 0x91, 0x6b, 0x21, 0x82, 0xcc, 0xbb, 0x60, 0x72, 0xaa,
	0x88, 0x26, 0x12, 0xdb, 0xf2, 0xd3, 0x67, 0xb2, 0x25, 0x34, 0x20, 0xad, 0x83, 0xb4, 0x8e, 0x04,
	0x82, 0xe6, 0x55, 0x59, 0x37, 0x5f, 0xd5, 0x15, 0xd8, 0xc5, 0x5b, 0x78, 0x42, 0xf0, 0x9d, 0x6a,
	0xb5, 0xdd, 0x6a, 0x77, 0xb2, 0xea, 0x8d, 0xac, 0xc7, 0x70, 0x88, 0xc6, 0x9c, 0xf2, 0x35, 0xe5,
	0xf3, 0x84, 0xe5, 0xce, 0xc1, 0xa8, 0x35, 0xb6, 0xc2, 0x9e, 0x84, 0x67, 0x88, 0xfa, 0x2c, 0x77,
	0x7f, 0x90, 0x0f, 0x83, 0xe9, 0xc8, 0x17, 0xd0, 0xfa, 0x95, 0x6e, 0x30, 0x8b, 0x3d, 0xf9, 0xb8,
	0xaa, 0x71, 0x3b, 0x19, 0xa1, 0xb4, 0x93, 0x63, 0x68, 0xad, 0xa3, 0x14, 0x13, 0xda, 0x93, 0x3b,
	0x4d, 0x37, 0x59, 0x74, 0x28, 0x1d, 0xdc, 0xdf, 0x35, 0x00, 0x6f, 0xb1, 0x08, 0xe9, 0xfb, 0x15,
	0xcd, 0x05, 0x19, 0x83, 0x21, 0x36, 0x8c, 0x62, 0xf8, 0xfe, 0x3e, 0xef, 0x7c, 0xc3, 0x68, 0x88,
	0x1e, 0x65, 0x1d, 0xfa, 0x7f, 0xab, 0xa3, 0x75, 0x53, 0x1d, 0x3f, 0x01, 0x4c, 0x69, 0xfa, 0x7f,
	0x95, 0xe1, 0x3e, 0x07, 0xfb, 0x8c, 0x8a, 0x90, 0xe6, 0x2c, 0x5b, 0xe6, 0x94, 0x7c, 0x0d, 0x9d,
	0x5c, 0x79, 0xe4, 0x8e, 0x36, 0x6a, 0x8d, 0xed, 0xc9, 0xa0, 0x49, 0x0d, 0x2b, 0x0f, 0xd7, 0x87,
	0x9e, 0x27, 0x44, 0x14, 0x5f, 0xde, 0xbe, 0x3c, 0xa5, 0x52, 0xbd, 0x54, 0xa9, 0x7b, 0x0c, 0xe6,
	0x2c, 0x5a, 0xd3, 0x90, 0xbe, 0x97, 0x83, 0x71, 0x91, 0xa4, 0x74, 0xce, 0x22, 0x71, 0x59, 0x2a,
	0x4c, 0x02, 0x41, 0x24, 0x2e, 0xdd, 0x6f, 0xc0, 0x0e, 0xb2, 0xf4, 0xf6, 0xf7, 0xe1, 0xfe, 0xad,
	0x41, 0x57, 0x31, 0x8b, 0x56, 0x4f, 0xa1, 0xbb, 0x8c, 0xc4, 0x3c, 0x57, 0xba, 0xbe, 0xae, 0x5d,
	0x34, 0x84, 0xf6, 0x32, 0x12, 0xc5, 0x39, 0x27, 0xcf, 0xa0, 0x77, 0xb1, 0xc3, 0xd2, 0xff, 0x85,
	0xd5, 0xbd, 0xa8, 0xd3, 0xbe, 0x84, 0x43, 0xc1, 0xa3, 0x65, 0x2e, 0x67, 0x7d, 0xfe, 0x0b, 0xcf,
	0x56, 0xcc, 0xe9, 0x62, 0x63, 0xfd, 0x0a, 0x3e, 0x93, 0x28, 0x71, 0xc0, 0x5c, 0x53, 0x2e, 0x49,
	0x4e, 0x4f, 0xc9, 0xa5, 0xf8, 0x74, 0xff, 0xd2, 0xc0, 0x0e, 0x56, 0x79, 0x75, 0xd5, 0x1f, 0x58,
	0xf9, 0x8f, 0xe1, 0xee, 0x19, 0x15, 0x6a, 0x5a, 0xe8, 0xc2, 0x5b, 0x2c, 0x78, 0xf5, 0x10, 0x77,
	0xe0, 0x20, 0x5a, 0x2c, 0xb8, 0x6a, 0xc1, 0x0a, 0xd5, 0x87, 0xfb, 0x0c, 0x06, 0xaf, 0x29, 0x65,
	0x5e, 0x9a, 0xe0, 0x54, 0x60, 0xcf, 0x0f, 0xa0, 0x9b, 0x2c, 0x05, 0xe5, 0x6b, 0xdc, 0x0c, 0x31,
	0xbe, 0x7a, 0x2f, 0xb4, 0x4b, 0x6c, 0x46, 0x63, 0x77, 0x02, 0x47, 0x35, 0x5a, 0x91, 0xe1, 0x3e,
	0xc0, 0x8a, 0x89, 0xe4, 0x8a, 0x56, 0x2c, 0x23, 0xb4, 0x14, 0x32, 0xa3, 0xf1, 0xc3, 0x47, 0xd5,
	0xce, 0x92, 0xf3, 0x42, 0x6c, 0x30, 0xa7, 0x2f, 0x5f, 0x79, 0xef, 0xde, 0x9c, 0x0f, 0x3e, 0x22,
	0x26, 0xb4, 0xde, 0x7a, 0xe7, 0x03, 0x8d, 0x74, 0xc0, 0x78, 0x25, 0x4f, 0xfa, 0xc3, 0xaf, 0xa0,
	0x53, 0x2e, 0x3e, 0xe9, 0xeb, 0xbf, 0xfd, 0xce, 0x7b, 0xe3, 0x4f, 0x95, 0xef, 0xf9, 0x8b, 0x60,
	0xd0, 0x96, 0x87, 0x77, 0xd3, 0x60, 0x70, 0x34, 0xf9, 0xc3, 0x00, 0xf3, 0xfb, 0x88, 0x33, 0x8f,
	0x25, 0xe4, 0x09, 0xb4, 0x55, 0xfb, 0xe4, 0xd3, 0xea, 0xba, 0x77, 0xd4, 0x33, 0xec, 0x57, 0x38,
	0xfe, 0xd7, 0x24, 0x63, 0x4a, 0x6f, 0xc5, 0x78, 0x8a, 0x3b, 0xab, 0xdc, 0x88, 0x5b, 0xd5, 0x6f,
	0x17, 0xd9, 0x1e, 0x65, 0x02, 0x70, 0x46, 0x45, 0x49, 0x69, 0x58, 0x87, 0x5b, 0x45, 0xd5, 0xb7,
	0xc4, 0x53, 0xdc, 0x49, 0xfb, 0x69, 0xb6, 0x8b, 0x6a, 0x2f, 0xcd, 0x18, 0x0c, 0xa9, 0x6f, 0x52,
	0x1b, 0x35, 0x25, 0xf7, 0x3d, 0xcf, 0x53, 0x30, 0xa4, 0x4e, 0xc9, 0x36, 0x75, 0x4d, 0xf0, 0xc3,
	0x4f, 0x1a, 0x68, 0xb5, 0xb7, 0x0c, 0x29, 0x8e, 0x3a, 0x69, 0xab, 0x95, 0xbd, 0x14, 0x2f, 0xe0,
	0xb0, 0x31, 0x8c, 0x7b, 0x8d, 0x8f, 0xea, 0x8d, 0x5f, 0x3b, 0xb6, 0x53, 0xb0, 0xaa, 0x49, 0x23,
	0xf7, 0x2a, 0xf7, 0xe6, 0xd0, 0x0e, 0x87, 0xd7, 0x99, 0x54, 0x8c, 0x27, 0xda, 0xb7, 0xdd, 0x1f,
	0xe1, 0xe4, 0xf1, 0xf3, 0xc2, 0xe3, 0xe7, 0x36, 0xfe, 0x47, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xf0, 0x78, 0x4f, 0x18, 0xf0, 0x08, 0x00, 0x00,
}
